# -- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FEE
FROM
(SELECT CAR_ID, CAR_TYPE, floor(daily_fee * 30 * (1-DISCOUNT_RATE/100)) AS FEE
FROM
    (SELECT *, '30일 이상' AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE > '2022-11-30' OR END_DATE < '2022-11-01')
        AND CAR_TYPE IN ('SUV', '세단')) AS CAR_RENTAL_COMPANY_CAR
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (CAR_TYPE, DURATION_TYPE)) AS RESULT
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;



# SELECT *, '30일 이상' AS DURATION_TYPE
#     FROM CAR_RENTAL_COMPANY_CAR 
#     WHERE CAR_ID IN (SELECT CAR_ID 
#                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#                      WHERE START_DATE > '2022-11-30' OR END_DATE < '2022-11-01'
#                         AND )
                        
# SELECT *, '30일 이상' AS DURATION_TYPE
# FROM CAR_RENTAL_COMPANY_CAR 
# WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE > '2022-11-30' OR END_DATE < '2022-11-01')
#     AND CAR_TYPE IN ('SUV', '세단')
# SELECT CAR_ID, CAR_TYPE, FEE FROM
# (SELECT *,floor(daily_fee * 30 * (1-IFNULL(DISCOUNT_RATE,0)/100)) AS FEE
# FROM 
#     (SELECT *,
#         CASE 
#             WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 1 and 6 THEN ''
#             WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 and 29 THEN '7일 이상'
#             WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 and 89 THEN '30일 이상'
#             ELSE '90일 이상'
#             END AS DURATION_TYPE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE > '2022-11-30' OR END_DATE < '2022-11-01'
#     ) AS CAR_RENTAL_COMPANY_RENTAL_HISTORY
# INNER JOIN CAR_RENTAL_COMPANY_CAR USING (CAR_ID)
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (DURATION_TYPE, CAR_TYPE)) AS result_ALL
# WHERE FEE >= 500000 AND FEE < 2000000 AND CAR_TYPE IN ('세단', 'SUV')
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;




# WHERE CAR_TYPE IN ('세단', 'SUV') AND FEE >300
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;