# -- 코드를 입력하세요
SELECT HISTORY_ID, floor(daily_fee * (DATEDIFF(END_DATE, START_DATE) + 1) * (1-IFNULL(DISCOUNT_RATE,0)/100)) AS FEE
FROM 
    (SELECT *,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 1 and 6 THEN ''
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 and 29 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 and 89 THEN '30일 이상'
            ELSE '90일 이상'
            END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS CAR_RENTAL_COMPANY_RENTAL_HISTORY
INNER JOIN CAR_RENTAL_COMPANY_CAR USING (CAR_ID)
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (DURATION_TYPE, CAR_TYPE)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;

    
-- INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING (CAR_TYPE)
# INNER JOIN CAR_RENTAL_COMPANY_CAR USING (CAR_ID)

# SELECT CAR_TYPE

# FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR)
#     AS test;



# SELECT CAR_TYPE, DISCOUNT_RATE,
#         CASE LEFT(DURATION_TYPE, 1)
#             WHEN 7 THEN '0729'
#             WHEN 3 THEN '3089'
#             ELSE '90'
#         END AS 'rangeDate'
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN;

# SELECT * 
# FROM CAR_RENTAL_COMPANY_CAR  
# INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (CAR_TYPE)
# WHERE CAR_TYPE = 

# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR
# INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING (CAR_ID)
# INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  USING (CAR_TYPE)